package com
 
import com.crawler.Equipo;
import java.util.*

// PG, PE, PP de local
rule "promedio partido ganado de local"
dialect "mvel"
when
	$class : Equipo(esLocal == true, promedioPartidoGanadoLocal > 0.6)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio partido ganado de local.");
	$class.sumarPuntaje(20);
end

rule "promedio partido empatado de local"
dialect "mvel"
when
	$class : Equipo(esLocal == true, promedioPartidoEmpatadoLocal > 0.5)
then
	System.out.println("Equipo: " + $class.nombre + " resta en Rule: promedio partido empatado de local.");
	$class.restarPuntaje(20);
end

rule "promedio partido perdido de local"
dialect "mvel"
when
	$class : Equipo(esLocal == true,  promedioPartidoPerdidoLocal < 0.15)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio partido perdido de local.");
	$class.sumarPuntaje(20);
end

// PG, PE, PP de visita
rule "promedio partido ganado de visita"
dialect "mvel"
when
	$class : Equipo(esLocal == false, promedioPartidoGanadoVisita > 0.5)
then
	System.out.println("Equipo: " + $class.nombre " suma en Rule: promedio partido ganado de visita.");
	$class.sumarPuntaje(20);
end

rule "promedio partido empatado de visita"
dialect "mvel"
when
	$class : Equipo(esLocal == false, promedioPartidoEmpatadoVisita > 0.5)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio partido empatado de visita.");
	$class.sumarPuntaje(5);
end

rule "promedio partido perdido de visita"
dialect "mvel"
when
	$class : Equipo(esLocal == false,  promedioPartidoPerdidoVisita < 0.15)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio partido perdido de visita.");
	$class.sumarPuntaje(20);
end

// GF GC de local
rule "promedio de gol a favor de local"
dialect "mvel"
when
	$class : Equipo(esLocal == true, promedioGolesAFavorLocal > 1.75)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio de gol a favor de local.");
	$class.sumarPuntaje(20);
end

rule "promedio de gol en contra de local"
dialect "mvel"
when
	$class : Equipo(esLocal == true,  promedioGolesEncontraLocal < 1.0)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio de gol en contra de local.");
	$class.sumarPuntaje(20);
end

// GF GC de visita
rule "promedio de gol a favor de visita"
dialect "mvel"
when
	$class : Equipo(esLocal == false, promedioGolesAFavorVisita > 1.5)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio de gol a favor de visita.");
	$class.sumarPuntaje(20);
end

rule "promedio de gol en contra de visita"
dialect "mvel"
when
	$class : Equipo(esLocal == false,  promedioGolesEncontraVisita < 1.0)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio de gol en contra de visita.");
	$class.sumarPuntaje(20);
end

// Puntos de local
rule "promedio de puntos de local"
dialect "mvel"
when
	$class : Equipo(esLocal == true, promedioPuntosLocal > 1.6)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio de puntos de local.");
	$class.sumarPuntaje(20);
end

// Puntos de visita
rule "promedio de puntos de visita"
dialect "mvel"
when
	$class : Equipo(esLocal == false,  promedioPuntosVisita > 1.3)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio de puntos de visita.");
	$class.sumarPuntaje(20);
end

// Puntos totales
rule "promedio de puntos totales"
dialect "mvel"
when
	$class : Equipo(promedioPuntosTotales > 1.5)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: promedio de puntos totales.");
	$class.sumarPuntaje(20);
end

// Reglas sobre tipo de equipo
rule "equipo grande"
dialect "mvel"
when
	$class : Equipo(esEquipoGrande == true)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: equipo grande.");
	$class.sumarPuntaje(5);
end

rule "BOCA"
dialect "mvel"
when
	$class : Equipo(esBoca == true)
then
	System.out.println("Equipo: " + $class.nombre + " suma en  Rule: BOCA");
	$class.sumarPuntaje(5);
end

rule "RIVER"
dialect "mvel"
when
	$class : Equipo(esRiver == true)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: RIVER");
	$class.sumarPuntaje(5);
end

rule "LOCAL"
dialect "mvel"
when
	$class : Equipo(esLocal == true)
then
	System.out.println("Equipo: " + $class.nombre + " suma en Rule: LOCAL");
	$class.sumarPuntaje(5);
end





